### ISSUE TITLE
Rename Organization to DistributedWeaknessFiling

### ISSUE THREAD

**Issue by JLLeitschuh** [distributedweaknessfiling/dwf-request#15]
Suggestion, before you get too much further, change the name of your organization to "DistributedWeaknessFiling" or consider using snake-case.

IMHO It looks more professional

**Comment by joshbressers** [comment]
I would be most disappointed to be mistakenly identified as a professional ;)

**Comment by JLLeitschuh** [comment]
Ah, in that case, it's a shame that GitHub doesn't support emojis in organization/repository names 😆
