### ISSUE TITLE
For historical issues we need to support selecting a year in the past

### ISSUE THREAD

**Issue by kurtseifried** [distributedweaknessfiling/dwf-request#45]
For historical issues, we need to support selecting a year in the past

I think the CVE-YEAR-XXXXXXX format is weak, but it's what people are used to. Providing a year selector (with a default of this year) seems like an easy way to implement this.

**Comment by kurtseifried** [comment]
I'm also having second thoughts about this, the CVE-YEAR thing typically results in poorly mangled statistics at best, is there any real value to knowing the year the issue we "found" as opposed to simply the date the CVE was assigned? For historical issues chasing down the years is more work than simply not doing it.

**Comment by kurtseifried** [comment]
Also see what people think: https://twitter.com/kurtseifried/status/1384208522540249088

**Comment by joshbressers** [comment]
I'm not a fan. I think the YEAR is just an integer in the ID. We are using it for legacy reasons

**Comment by kurtseifried** [comment]
Ok so for now I suggest we just use the current YEAR for when the legacy CVE identifier is assigned and we put the actual data (if it matters) into the JSON.
