### ISSUE TITLE
`https://iwantacve.org` is unreachable.

### ISSUE THREAD

**Issue by dzrtc** [distributedweaknessfiling/dwf-request#54]
Is this a problem with the documentation or the site?

**Comment by kurtseifried** [comment]
We'll be making an announcement in the next week or two that covers this, but TL;DR: we had to shut it down and we'll be transferring it to the MITRE Corporation and hopefully they will choose to make it available.

**Comment by dzrtc** [comment]
Sorry to hear that.  Sounds like they're hitting you guys pretty hard over the term CVE.
